title:            A Hungry Hipster
description:      Always leave room for dessert.
logo:             site-logo.png
disqus_shortname: ahungryhipster
search:           true
#Change url to your domain. Leave localhost server or blank when working locally.

# Owner/author information
owner:
  name:           Jennifer Kim
  avatar:         Jenny.jpg
  email:          jenn@ahungryhipster.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        ahungryhipster
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Restaurants
    url: /restaurants
  - title: About
    url: /about
  - title: Articles
    url: /articles

#prose online editing tool
prose:
    root: '_posts'
    siteurl: 'http://www.ahungryhipster.com'
    media: 'images'
    metadata:
        _posts:
          - name: "layout"
            field:
              element: "hidden"  
              value: "post"
          - name: "comments"
            field:
              element: "hidden"
              value: "true"
          - name: "category"
            field:
                value: "articles"
                
              - name: "image"
                    field:
                      element: "text"
                      label: "test"
                      value: ""
          - name: "tag"
            field:
              element: "text"
              label: "Tag"
              value: ""            
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
